### ISSUE TITLE
An exception occured: KeyError: 'total_bytes'

### ISSUE THREAD

**Issue by owcz** [Toollabs/video2commons#8]
I'm getting this error on an upload, but there is no explanation of why it is occurring.

I tried clicking "Restart" twice, but it fails each time. Any tips? Or perhaps it would be worth changing the error to explain what to do differently?

**Comment by zhuyifei1999** [comment]
Bug related to fragmented media:
```
[2016-02-29 14:22:32,072: INFO/MainProcess] Received task: worker.main[32dfdfdc-b2ff-4f45-9364-bbe8b850d61e]
[2016-02-29 14:22:32,087: WARNING/Worker-3] -1: Downloading...
[2016-02-29 14:22:32,090: WARNING/Worker-3] -1: Creating YoutubeDL instance
[2016-02-29 14:22:32,092: WARNING/Worker-3] WARNING: Parameter outtmpl is bytes, but should be a unicode string. Put  from __future__ import unicode_literals  at the top of your code file or consider switching to Python 3.x.
[2016-02-29 14:22:32,363: WARNING/Worker-3] -1: Preprocessing...
[2016-02-29 14:22:32,386: WARNING/Worker-3] [youtube] W2jPu4bgW5I: Downloading webpage
[2016-02-29 14:22:32,738: WARNING/Worker-3] [youtube] W2jPu4bgW5I: Downloading video info webpage
[2016-02-29 14:22:32,898: WARNING/Worker-3] [youtube] W2jPu4bgW5I: Extracting video information
[2016-02-29 14:22:33,008: WARNING/Worker-3] WARNING: video doesn't have subtitles
[2016-02-29 14:22:33,011: WARNING/Worker-3] [youtube] W2jPu4bgW5I: Downloading MPD manifest
[2016-02-29 14:22:33,239: WARNING/Worker-3] [youtube] W2jPu4bgW5I: Downloading MPD manifest
[2016-02-29 14:22:33,384: WARNING/Worker-3] [info] Writing video description to: /srv/v2c/output/7667a4286c99f334/dl.description
[2016-02-29 14:22:33,384: WARNING/Worker-3] [info] Writing video description metadata as JSON to: /srv/v2c/output/7667a4286c99f334/dl.info.json
[2016-02-29 14:22:33,563: WARNING/Worker-3] [dashsegments] Total fragments: 45
[2016-02-29 14:22:33,564: WARNING/Worker-3] [download] Destination: /srv/v2c/output/7667a4286c99f334/dl.f137.mp4
[2016-02-29 14:22:33,597: WARNING/Worker-3] [download]   2.2% of ~36.47KiB at Unknown speed ETA 00:01
[2016-02-29 14:22:33,597: WARNING/Worker-3] -1: Cleaning up...
[2016-02-29 14:22:33,606: ERROR/MainProcess] Task worker.main[32dfdfdc-b2ff-4f45-9364-bbe8b850d61e] raised unexpected: KeyError('total_bytes',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/v2c/backend/worker.py", line 94, in main
    outputdir, statuscallback, errorcallback
  File "/srv/v2c/backend/download/__init__.py", line 72, in download
    info = dl.extract_info(url, download=True, ie_key=ie_key)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 677, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 722, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1362, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1618, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1566, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 343, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/dash.py", line 49, in real_download
    append_url_to_file(initialization_url, ctx['tmpfilename'] + '-Init')
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/dash.py", line 40, in append_url_to_file
    success = ctx['dl'].download(target_filename, {'url': combine_url(base_url, target_url)})
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 343, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 222, in real_download
    'elapsed': now - start,
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 351, in _hook_progress
    ph(status)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/fragment.py", line 104, in frag_progress_hook
    self._hook_progress(state)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 351, in _hook_progress
    ph(status)
  File "/srv/v2c/backend/download/__init__.py", line 57, in progresshook
    if d['total_bytes'] else None
KeyError: 'total_bytes'
```
Will add a workaround + report documentation issue upstream tomorrow.

**Comment by owcz** [comment]
Thanks! If it helps, I ultimately uploaded [the video](https://www.youtube.com/watch?v=W2jPu4bgW5I) [manually](https://commons.wikimedia.org/wiki/File:Bernie_Sanders_Chicago_HQ_2016-02-17.webm).

**Comment by zhuyifei1999** [comment]
Fixed in 80beeea22dd01ccb1df8f61f1cd8ec87c5a9335f, and deployed to encoding01; waiting for tasks on encoding02 to finish before deployment.

**Comment by zhuyifei1999** [comment]
Reported [upstream bug](https://github.com/rg3/youtube-dl/issues/8711).

**Comment by zhuyifei1999** [comment]
Deployed on encoding02

**Comment by zhuyifei1999** [comment]
Deployed on encoding02

**Comment by zhuyifei1999** [comment]
Deployed on encoding02

**Comment by zhuyifei1999** [comment]
Deployed on encoding02

**Comment by zhuyifei1999** [comment]
Deployed on encoding02
